site_name: Platformer Documentation
repo_name: "platformercloud/platformer-docs"
repo_url: "https://github.com/platformercloud/platformer-docs"
site_url: "https://docs.platformer.com"
site_description: "The Cloud Native Application Platform built for Kubernetes."
theme:
  features:
    - tabs
    - instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections
  include_sidebar: true
  name: material
  custom_dir: overrides
  favicon: assets/images/favicon.ico
  logo: assets/images/platformer-logo.png
  palette:
    - scheme: default
      primary: indigo
      accent: blue grey
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: slate
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

plugins:
  - search
  - awesome-pages


markdown_extensions:
  - smarty
  - toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - "Welcome":
       - Overview: "index.md"
       - Getting started: "getting-started.md"
       - How it works: "how-it-works.md"
       - CLI: "cli.md"
       - Support: "support.md"
  - ...